### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by ghost** [rioj7/select-by#15]
I need to select the text between quotes, like sublime text does

```js
<img src="https://someimage.com/something.png"/>
```

To get this:

```js
https://someimage.com/something.png
```

**Comment by rioj7** [comment]
@alexander-vashchuk 

It should work if you use the following properties

```
      {
        "forward": "\"",
        "forwardInclude": false,
        "backward": "\"",
        "backwardInclude": false
      }
```

You can add these properties to a key binding or to the list of predefined (name) settings, see the Extension page (README file) for details depending on how you want to use it.

place the cursor in the string and execute the `selectby.regex` command.

If there is a possibility that the string contains an escaped `"` you need to add a negative lookbehind 

```
      {
        "forward": "(?<!\\\\)\"",
        "forwardInclude": false,
        "backward": "(?<!\\\\)\"",
        "backwardInclude": false
      }
```

**Comment by ghost** [comment]
How to make it work also, for all kind of quotes
double "
single '
interpolation `

**Comment by ghost** [comment]
Am I doing everything correctly?

![image](https://user-images.githubusercontent.com/86713661/173021316-395f6d54-da93-468a-9ab6-b1b379885eac.png)

It seems to work for me

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/86713661/173021493-bb90bf2c-ef8a-4c7a-b2bd-97954b7930ec.png)
Why changing regex name is throwing an issue
?

**Comment by rioj7** [comment]
@alexander-vashchuk 

If you use the commands `selectby.regex1` ... `selectby.regex5` you don't need to give arguments because it is implicit with the name, it uses key `regex1` ... `regex5`.

If you name the key `regex1000` you have to use the command `selectby.regex` with an argument specifying the key name.

``` json
{
    "key": "ctrl+alt+d",
    "when": "editorTextFocus",
    "command": "selectby.regex",
    "args": ["regex1000"]
  }
```

you can also put the regex definition in the keybinding as an object argument.

``` json
{
    "key": "ctrl+alt+d",
    "when": "editorTextFocus",
    "command": "selectby.regex",
    "args": {
        "forward": "\"",
        "forwardInclude": false,
        "backward": "\"",
        "backwardInclude": false
      }
  }
```

If you want to handle different string literal delimeter characters you have to define an **Alternate Option** regex:

``` json
{
    "key": "ctrl+alt+d",
    "when": "editorTextFocus",
    "command": "selectby.regex",
    "args": {
        "forward": "\"|'|`",
        "forwardInclude": false,
        "backward": "\"|'|`",
        "backwardInclude": false
      }
  }
```

This can give incorrect results if you use some of these characters inside a string delimeter like  `'Hello "World"!'`.

But these cases are rare in programs.
